import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
const json = async (path) => JSON.parse(await readFile(path, 'utf8'));
const manifest = await json('manifest.json');
const pkg = await json('package.json');
const versions = await json('versions.json');
assert.match(manifest.version, /^\d+\.\d+\.\d+$/);
assert.equal(manifest.version, pkg.version);
assert.equal(versions[manifest.version], manifest.minAppVersion);
assert.equal(manifest.isDesktopOnly, true);
assert.ok(!manifest.id.includes('obsidian'));
assert.ok(manifest.description.length <= 250 && manifest.description.endsWith('.'));
const files = (await readdir('dist/pdf-selection-translator')).sort();
assert.deepEqual(files, ['main.js', 'manifest.json', 'styles.css']);
assert.deepEqual(await json('dist/pdf-selection-translator/manifest.json'), manifest);
const bundle = await readFile('dist/pdf-selection-translator/main.js', 'utf8');
assert.equal(await readFile('dist/main.js', 'utf8'), bundle);
assert.ok(bundle.includes('MIT'));
assert.ok(!bundle.includes('local-ui-test'));
assert.ok(!bundle.includes('Mock request accepted'));
assert.ok(!bundle.includes('test-only-key'));
console.log(`Release ${manifest.version}: manifest, version map and three installable assets verified.`);
